//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character
{
   
    public virtual Execute Execute
	{
		get;
		set;
	}

	public virtual void Order(int n)
	{
        Execute horse_div = new HorseDivision();
        Execute solder_div = new SolderDivision();
        Execute shoot_div = new ShooterDivision();
        Execute dragon_div = new DragonDivision();
        
        solder_div.Executer = horse_div;
        horse_div.Executer = shoot_div;
        shoot_div.Executer = dragon_div;
        solder_div.OrderRequest(n);
     

    }

}

