//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SolderDivision : Execute
{
    public override void OrderRequest(int Condition)
    {
        if (Condition == 2)
            Console.WriteLine("Ura Ura. I do it");
        else if (Executer != null)
        {
            Executer.OrderRequest(Condition);

        }

    }
}

